### PR TITLE
style tweaks, ui improvements, added few components

### PR DESCRIPTION
**Pull request by daubaris**
#33 changed styles a bit, added a few components. If you could elaborate on: 

- Nice encrypted messages (filter out encrypted and just say encrypted? Map to words?)
- More intuitive encryption input process

I could fix them also :).

### CODE REVIEW

**Comment by robertDurst** [comment]
Awesome looks great so far! Thanks again for the contribution. 

One thing I noticed is that received messages have a green background -- my thinking is that only received messages for your public key should be green (messages you decrypt). Messages encrypted to other public key should be gray or some other background color.

> Nice encrypted messages (filter out encrypted and just say encrypted? Map to words?)

Sort of going along with the comment above, the way the app works is if the received message is prefixed with the user's public key, his app will try to decrypt the message. For messages received and not prefixed with this key, they are just shown in plaintext (ALOT of plaintext since it is the encrypted message). I was thinking there may be a better way to do this... 
* I fix the encryption so it doesn't encrypt each char individually -- see #39 
* Map the ciphertext to words or something so that it is shorter and more user friendly
* Filter out these messages and instead of showing the entire ciphertext, just say "encrypted message" or "unable to decrypt" or "encrypted message for someone else" or something like that

> More intuitive encryption input process

The current process for encrypting messages is the user inputs the entire public key of the message recipient (parenthesis included) and puts this in the encrypt field and then puts the message in the send field. Then the user clicks the encrypt button and the message is encrypted and fills in the send field. Finally, the user clicks send. This is NOT intuitive.

I have many ideas for making this better such as:
* being able to click on user's public keys and auto fill the encrypt field
* better fields (more intuitive)
* mapping public keys to something more obvious or user friendly like a short, auto-generated username

Also, this goes along the lines of user discoverability. Another part of this open issue is letting the user know who else is online. Again, lots of ways to do this :)

**Open to any ideas you have or ways you think are better!** I'll be honest, I copied the tutorial from socket.io as a base and spent most of my time so far on the rust 😃

**Comment by robertDurst** [comment]
If the rebase is nasty (sorry made a few changes to the crypto/frontend yesterday) let me know. I can figure this out.

**Comment by daubaris** [comment]
Oh sorry. I've created a new PR. Had some problems with branches while trying out gihtub desktop...

**Comment by robertDurst** [comment]
No worries! Checking it out now.

**Pull request closed without merging**
